"""Initial schema

Revision ID: ce8eca1682b2
Revises: 
Create Date: 2026-01-26 05:25:33.146630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce8eca1682b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gyms',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('members',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('gym_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('join_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gym_id', 'phone_number', name='uq_member_phone_per_gym')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_members_gym_id'), ['gym_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_members_join_date'), ['join_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_members_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_members_phone_number'), ['phone_number'], unique=False)

    op.create_table('plans',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('gym_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gym_id', 'name', name='uq_plan_name_per_gym')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plans_gym_id'), ['gym_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plans_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('gym_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Enum('owner', 'staff', name='user_roles'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_gym_id'), ['gym_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_phone_number'), ['phone_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('memberships',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('member_id', sa.String(length=50), nullable=False),
    sa.Column('gym_id', sa.String(length=50), nullable=False),
    sa.Column('plan_id', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'cancelled', name='membership_status'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_gym_id'), ['gym_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_status'), ['status'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('gym_id', sa.String(length=50), nullable=False),
    sa.Column('membership_id', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'upi', name='payment_methods'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', name='payment_status'), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_gym_id'), ['gym_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_membership_id'), ['membership_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_paid_at'), ['paid_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_paid_at'))
        batch_op.drop_index(batch_op.f('ix_payments_membership_id'))
        batch_op.drop_index(batch_op.f('ix_payments_gym_id'))
        batch_op.drop_index(batch_op.f('ix_payments_created_at'))

    op.drop_table('payments')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_status'))
        batch_op.drop_index(batch_op.f('ix_memberships_plan_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_member_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_gym_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_end_date'))
        batch_op.drop_index(batch_op.f('ix_memberships_created_at'))

    op.drop_table('memberships')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_phone_number'))
        batch_op.drop_index(batch_op.f('ix_users_name'))
        batch_op.drop_index(batch_op.f('ix_users_gym_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_name'))
        batch_op.drop_index(batch_op.f('ix_plans_gym_id'))

    op.drop_table('plans')
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_members_phone_number'))
        batch_op.drop_index(batch_op.f('ix_members_name'))
        batch_op.drop_index(batch_op.f('ix_members_join_date'))
        batch_op.drop_index(batch_op.f('ix_members_gym_id'))

    op.drop_table('members')
    op.drop_table('gyms')
    # ### end Alembic commands ###
