"""fixing member constraint

Revision ID: 07db69bf4685
Revises: 1f35b5ac5e14
Create Date: 2026-02-15 16:19:47.431636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07db69bf4685'
down_revision = '1f35b5ac5e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_member_phone_per_gym'), type_='unique')
        batch_op.create_unique_constraint('uq_member_phone_per_gym', ['gym_id', 'phone_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_constraint('uq_member_phone_per_gym', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_member_phone_per_gym'), ['gym_id'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
