"""Added Image URL

Revision ID: 1f35b5ac5e14
Revises: 
Create Date: 2026-02-15 05:54:07.555225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f35b5ac5e14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=200), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_member_phone_per_gym'), type_='unique')
        batch_op.create_unique_constraint('uq_member_phone_per_gym', ['gym_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_constraint('uq_member_phone_per_gym', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_member_phone_per_gym'), ['gym_id', 'phone_number'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
