"""Adding discount field

Revision ID: 43519605b460
Revises: cab291aa5757
Create Date: 2026-02-24 10:33:24.049398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43519605b460'
down_revision = 'cab291aa5757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_price', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('discount_amount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('amount_paid', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('effective_price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_column('effective_price')
        batch_op.drop_column('amount_paid')
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('original_price')

    # ### end Alembic commands ###
