"""ix phone nullable and partial index

Revision ID: 6640e63f41b8
Revises: 6e85622aaf28
Create Date: 2026-02-15 16:42:46.093447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6640e63f41b8'
down_revision = '6e85622aaf28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
