"""Added Tokens for reseting password

Revision ID: 6d5fbbac599a
Revises: 6640e63f41b8
Create Date: 2026-02-18 04:09:17.775662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d5fbbac599a'
down_revision = '6640e63f41b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('token_expiry', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gyms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('token_expiry')
        batch_op.drop_column('token')

    # ### end Alembic commands ###
