"""partial unique index for member phone

Revision ID: 6e85622aaf28
Revises: 07db69bf4685
Create Date: 2026-02-15 16:30:14.702555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e85622aaf28'
down_revision = '07db69bf4685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_member_phone_per_gym'), type_='unique')
        batch_op.create_index('uq_member_phone_per_gym', ['gym_id', 'phone_number'], unique=True, postgresql_where=sa.text('phone_number IS NOT NULL'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_index('uq_member_phone_per_gym', postgresql_where=sa.text('phone_number IS NOT NULL'))
        batch_op.create_unique_constraint(batch_op.f('uq_member_phone_per_gym'), ['gym_id', 'phone_number'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
